### ISSUE TITLE
Baubles support? 

### ISSUE THREAD

**Issue by ArMoReDfUrY** [Wurmatron/Mining-Goggles#11]
I was wondering if you could make a baubles version of the mining goggles for the head/glasses slot?
it would make it better to use with modded armour sets and keep the goggle render on the character too.
maybe as a config option?.
the module system should work fine too.

**Comment by Wurmatron** [comment]
Module System is disabled while it's being used as a bauble to semi-balance what the goggles can do. AKA, not a single bauble to rule them all.

**Comment by ArMoReDfUrY** [comment]
that works for me, cant have it too powerful.
