### ISSUE TITLE
IC2 Ores can't be seen using Mining Goggles.

### ISSUE THREAD

**Issue by dwn780** [Wurmatron/Mining-Goggles#12]
For example, the Uranium ore is registered in the Ore Dictionary as oreUranium, and according Craftweaker it is ore:oreUranium or ic2:resource:4, even they was the correct thing i need to type into the boxes of the mining goggles, i can't, since i can't type ":" or numbers. I'm not sure if this is a bug, but I would appreciate it if you could help me.

**Comment by Wurmatron** [comment]
Feel free to msg me on discord if that will help

**Comment by Wurmatron** [comment]
https://www.wurmcraft.com
